// // user constants defines
export const ADD_LESSON = 'ADD_LESSON';
export const ADD_SUBJECTS = 'ADD_SUBJECTS';
export const ADD_CHAPTER = 'ADD_CHAPTER';
export const UPDATE_LESSON = 'UPDATE_LESSON';
export const UPDATE_SUBJECT_API = ' UPDATE_SUBJECT_API';
export const UPDATE_CHAPTERS_API = ' UPDATE_CHAPTERS_API';
export const UPDATE_LESSONS_API = ' UPDATE_LESSONS_API';
export const UPDATE_LESSONS_RUNTIME = ' UPDATE_LESSONS_RUNTIME';
export const UPDATE_PROGRESS = ' UPDATE_PROGRESS';
