// tasbeeh constants defines
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_SUB_CATEGORY = 'UPDATE_SUB_CATEGORY';
export const UPDATE_PROMPT_DETAILS = 'UPDATE_PROMPT_DETAILS';
export const UPDATE_SELECT_PROMPT_DETAILS = 'UPDATE_SELECT_PROMPT_DETAILS';
export const UPDTE_FRIENDS_PAGE_LIST = 'UPDATE_FRIENdS_PAGE_LIST';
export const ADD_QUEUE_QUEUE = 'ADD_QUEUE_QUEUE';
export const SET_CURRENT_STATE = 'SET_CURRENT_STATE';
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE';
export const SET_VIDEO_LIST = 'SET_VIDEO_LIST';
// user constants defines
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const LOGOUT_AUTH = 'LOGOUT_AUTH';
export const DELETE_AUTH = 'DELETE_AUTH';
export const UPDATE_VIDEO_VIEW = 'UPDATE_VIDEO_VIEW';
export const SET_VIDEO_VIEW = 'SET_VIDEO_VIEW';
export const SET_TUTORIAL_OPTION = 'SET_TUTORIAL_OPTION';
export const REQUEST_LOGIN_EMAIL_PASSWORD = 'REQUEST_LOGIN_EMAIL_PASSWORD';
export const SET_REQUEST_LOGIN_EMAIL_PASSWORD =
  'SET_REQUEST_LOGIN_EMAIL_PASSWORD';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const REQUEST_LOGIN_GOOGLE_SIGIN = 'REQUEST_LOGIN_GOOGLE_SIGIN';
export const REQUEST_SIGNUP_EMAIL_PASSWORD = 'REQUEST_SIGNUP_EMAIL_PASSWORD';
export const REQUEST_SIGNUP_GOOGLE_SIGIN = 'REQUEST_SIGNUP_GOOGLE_SIGIN';
export const REQUEST_LOGIN_APPLE_SIGIN = 'REQUEST_LOGIN_APPLE_SIGIN';
export const REQUEST_SIGNUP_APPLE_SIGIN = 'REQUEST_SIGNUP_APPLE_SIGIN';
export const UPDATE_ERROR_STATE = 'UPDATE_ERROR_STATE';
export const UPDATE_LAST_PROMPT = 'UPDATE_LAST_PROMPT_STATE';
export const SET_LAST_PROMPT = 'SET_LAST_PROMPT';
